### ISSUE TITLE
gooseberry make giving error

### ISSUE THREAD

**Issue by muralikodali** [out-of-cheese-error/gooseberry#31]
on Arch linux , compiled gooseberry after cloning repo and downloaded mdbook as seperate binary.
gooseberry sync and tag sub commands working without error.

gooseberry make giving the following error after creating src directory and book.toml 

> Error: No such file or directory (os error 2)

i tried running `gooseberry make` after creating Chapter_1.md and SUMMARY.md in knowledgebase directory,  which erased both files giving the same above error.

**Comment by Ninjani** [comment]
Hi, thanks for trying it out. I believe this is because [mdbook-mermaid](https://github.com/badboy/mdbook-mermaid) is not installed, could you try installing it and running `gooseberry make` again? If that works I'll add a better error message to point this out. 

Also, currently gooseberry erases files in the knowledgebase directory before creating its own (which is what happened to your Chapter_1 and summary) but I'll change this in the future (issue #10) so that external notes and gooseberry created notes can live side by side.

**Comment by muralikodali** [comment]
thanks for your suggestion. 
After installing mdbook-mermaid, it worked without any error.

**Comment by Ninjani** [comment]
Great! Added a suggestion to the error to make this clearer
