### ISSUE TITLE
Unsure about the acceptable characters for tags

### ISSUE THREAD

**Issue by ngirard** [out-of-cheese-error/gooseberry#79]
Okay, this is more of a question than an issue *per se*, but since I'm tring to get back to Hypothes.is and can't remember which characters can be part of a tag, I thought it could be worth adding that info to the docs.

(What I'm trying to come up with is a controlled vocabulary with facets, so something like `parent:child1` / `parent:child2` or `parent/child1` / `parent/child2` -- whatever form Hypothes.is would be nice enough to accept).

**Comment by Ninjani** [comment]
As far as I know hypothesis allows pretty much anything in a tag. I use the `parent/child1` method because I export to  Obsidian which uses "/" to specify tag hierarchy. Gooseberry doesn't allow the semicolon `;` character because it's used as the separator in the sled database (though this may change later with SQLite)

**Comment by ngirard** [comment]
Thanks ! I'm very fine with `/` as a delimiter, being an Obsidian user myself ;-)

**Comment by Ninjani** [comment]
Great! One point: you'll have to include the # that Obsidian needs either in the tag itself or in the annotation export template (I use it in the template since I feel it adds some visual clutter when looking at the annotation in the browser)

**Comment by ngirard** [comment]
Makes sense, thanks for the tip!
