### ISSUE TITLE
Unsure what happens after replying no to "Clear knowledge base directory?"

### ISSUE THREAD

**Issue by ngirard** [out-of-cheese-error/gooseberry#86]
I'd tempted to answer "no" to *"Clear knowledge base directory?"* when generating the knowledge base, but I don't know what whould happen in both situations:
- if the kb-related config has changed since the last generation ;
- if the kb-related config hasn't changed since the last generation.

**Comment by Ninjani** [comment]
Files are overwritten in both cases. I haven't handled the kb config change at all, so there'll be extra files in that case. The prompt is mainly to warn users that a directory will be cleared because I accidentally deleted a pretty important directory once :p Though now that I look again it doesn't actually tell you which directory until after you answer which is not very user-friendly...

**Comment by ngirard** [comment]
> Files are overwritten in both cases.

Do you mean that the whole kb dir is deleted & recreated, or that the files are left *as is* ?

**Comment by Ninjani** [comment]
On answering yes, the whole kb dir is deleted and recreated. On answering no, files are left as is but those with the same name are overwritten.

**Comment by ngirard** [comment]
Aha. I see, thanks !
